### ISSUE TITLE
Define Common Data format between AC3R and Post-Crash Analysis 

### ISSUE THREAD

**Issue by alessiogambi** [SoftLegend/AC3R-Demo#10]
AC3R will be run from python as component that generate the scenario in the common format. The python extension will takes this and translate it to a runnable scenarios. The Post-crash analysis will start from this representation to implement the search algorithm

**Comment by TriHuynh00** [comment]
For AC3R, the input into the CLI is a crash report, or an array of crash reports

**Comment by harveyvn** [comment]
This issue is solved with the PR https://github.com/TriHuynh00/AC3R-Demo/pull/13
