### ISSUE TITLE
Python Command Line Interface

### ISSUE THREAD

**Issue by alessiogambi** [SoftLegend/AC3R-Demo#11]
The new version will work by having python command line (e.g., using Click) that orchestrate and setup the other components: AC3R for info extraction and original scenario generation, Search for its evolution and the executor to interface with BeamNG

**Comment by TriHuynh00** [comment]
CLI is already implemented, add the following argument to AC3R executable command:

`--reports path/to/File1.xml path/to/File2.xml`

Note: if the file does not exist, it will be rejected and not processed.

There is a feature to get all XML in a folder as well. Append "*" as subfolder of the target directory. For example

`-reports path/to/directory1/* path/to/directory2/*`

Both single file selection and filtered selection can be used together:

`-reports path/to/directory1/* path/to/File1.xml`

@harveyvn Please merge the branch Tri_AC3R_GetReportsCLI into your current implementation, and check if it works correctly on your side 😉

**Comment by alessiogambi** [comment]
@TriHuynh00 great! Thanks.

**Comment by harveyvn** [comment]
This issue is solved with the PR https://github.com/TriHuynh00/AC3R-Demo/pull/13
