### ISSUE TITLE
Create JSON file from AC3R Street Object

### ISSUE THREAD

**Issue by TriHuynh00** [SoftLegend/AC3R-Demo#12]
First, create a JSON object storing the nodes of each road  in the following format:

{
  "v1_road": [{x1, y1,z1} ..., {xn, yn, zn}]
  "v2_road": [{x1, y1,z1} ..., {xn, yn, zn}]
  "v1_speed": [speed_1, ..., speed_n-1]
  "v2_speed": [speed_1, ..., speed_n-1]
}

The information of the road geometry can be found in the Street model, line 351 of AccidentConstructor class.

Second, create a parameter to specify the output location of this JSON file.

This JSON file is inputted into Sameed code to be processed.

**Comment by alessiogambi** [comment]
@TriHuynh00 Note that the arrays of speed should have one element less than the array of waypoints

**Comment by harveyvn** [comment]
This issue is solved with the PR https://github.com/TriHuynh00/AC3R-Demo/pull/13
