### ISSUE TITLE
Add Rotation Degree and Crash Point

### ISSUE THREAD

**Issue by TriHuynh00** [SoftLegend/AC3R-Demo#14]
Add rotation degree of each vehicle in the following format. The value or rotation is from 0 - 359

v1_rot_degree: 45
v2_rot_degree: 0

Crash point:
crash_point: [x, y, z]

**Comment by harveyvn** [comment]
If the scenario has 2 roads, looping the road_node_list and then categorizing them by their road_ID. The property name should be "road[road_ID]_node_list"

**Comment by harveyvn** [comment]
This issue has been solved in https://github.com/TriHuynh00/AC3R-Demo/pull/16
