### ISSUE TITLE
Compare new AC3R with old AC3R over the 7 case studies

### ISSUE THREAD

**Issue by alessiogambi** [SoftLegend/AC3R-Demo#33]
AC3R was generally good in creating the scenarios, why now the original scenario is not as good as before?

We need to compare the original scenarios between the systems.
Let's start to check the videos on YT:

https://www.youtube.com/channel/UCkje-B1ZfYgYC_k3biR7-WQ

**Comment by harveyvn** [comment]
Resolved in https://github.com/TriHuynh00/AC3R-Demo/pull/49
