### ISSUE TITLE
Collect Ground Truth Data About the Crash from the XML file

### ISSUE THREAD

**Issue by alessiogambi** [SoftLegend/AC3R-Demo#47]
We can look for tags like:
- STRIKER_AREA_DAMAGE
- HIT_AREA_DAMAGE

And extract information about the damaged component. Note this might require to match the vehicles in the simulation as striker/victim might not always be intuitive.

**Comment by harveyvn** [comment]
Resolved in https://github.com/TriHuynh00/AC3R-Demo/pull/49
