### ISSUE TITLE
Unexpected errors in case 3 and 4 JSON files

### ISSUE THREAD

**Issue by harveyvn** [SoftLegend/AC3R-Demo#77]
- Update expected crash components in case 3 and 4 JSON files
- Store combination of different speeds to log data
- Pick cases from AC3R CIREN JSON, create JSON files based on external.csv and use Random/OpO algorithms to evaluate

**Comment by alessiogambi** [comment]
@harveyvn Check that the JSON files of the other cases are consistent with their descriptions and sketches. Update the JSON files if necessary
